#ifndef BLIND_IPC_H
#define BLIND_IPC_H

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif

#include <Windows.h>

#define IXIPC_DEFAULT_HOOK_PIPE_NAME L"\\\\.\\pipe\\BLINDHookIngest"
#define IXIPC_HOOK_PIPE_NAME IXIPC_DEFAULT_HOOK_PIPE_NAME
#define IXIPC_PIPE_NAME_ENV L"BLIND_PIPE_NAME"
#define IXIPC_MAX_PIPE_NAME_CHARS 256
#define IXIPC_MAGIC 0x424C4E44u
#define IXIPC_VERSION 2u

#define IX_INSTRUMENTATION_RANGE_TAG_CHARS 64
#define IX_MAX_INSTRUMENTATION_TAG IX_INSTRUMENTATION_RANGE_TAG_CHARS
#define IX_HOOK_PATCH_TAG_CHARS 64
#define IX_MAX_HOOK_PATCH_BYTES 16
#define IX_MAX_IMAGE_PATH_CHARS 260

#define IX_INSTRUMENTATION_FLAG_SYSCALL_STUB 0x00000001u
#define IX_INSTRUMENTATION_FLAG_LAUNCH_GATE 0x00000002u
#define IX_INSTRUMENTATION_FLAG_PROCESS_CALLBACK 0x00000004u
#define IX_INSTRUMENTATION_FLAG_EXECUTABLE_HELPER 0x00000008u
#define IX_HOOK_PATCH_FLAG_NT_INLINE 0x00000001u
#define IX_HOOK_PATCH_FLAG_WINSOCK_IAT 0x00000002u
#define IX_HOOK_PATCH_FLAG_WINSOCK_INLINE 0x00000004u
#define IX_HOOK_PATCH_FLAG_KI_SLOT 0x00000008u
#define IX_HOOK_PATCH_FLAG_MODULE_INLINE 0x00000010u
#define IX_HOOK_PATCH_FLAG_NT_INT3 0x00000020u
#define IX_HOOK_PATCH_FLAG_MODULE_IAT 0x00000040u
#define IX_HOOK_PATCH_FLAG_MODULE_SHADOW_IAT 0x00000080u
#define IX_PROCESS_INSTRUMENTATION_CALLBACK_FLAG_X64 0x00000001u
#define IX_PROCESS_INSTRUMENTATION_CALLBACK_FLAG_SENSOR 0x00000002u

typedef enum _IX_IPC_PACKET_TYPE
{
    IxIpcPacketInvalid = 0,
    IxIpcPacketRequest = 1,
    IxIpcPacketResponse = 2
} IXIPC_PACKET_TYPE;

typedef enum _IX_IPC_COMMAND
{
    IxIpcCommandNone = 0,
    IxIpcCommandHandshake = 1,
    IxIpcCommandPublishHookEvent = 11,
    IxIpcCommandNotifyHookReady = 13,
    IxIpcCommandUpgradeWinsockHooks = 18,
    IxIpcCommandRegisterInstrumentationRange = 19,
    IxIpcCommandRegisterHookPatch = 20,
    IxIpcCommandRegisterProcessInstrumentationCallback = 25,
    IxIpcCommandPublishHookEventBatch = 26,
    IxIpcCommandQueryHookPolicy = 27
} IXIPC_COMMAND;

typedef struct _IX_IPC_HANDSHAKE_REQUEST
{
    UINT32 RequestedVersion;
} IXIPC_HANDSHAKE_REQUEST, *PIXIPC_HANDSHAKE_REQUEST;

typedef struct _IX_IPC_HANDSHAKE_RESPONSE
{
    UINT32 NegotiatedVersion;
    UINT32 Capabilities;
    UINT32 ThreatIntelEnabled;
    UINT32 Reserved;
} IXIPC_HANDSHAKE_RESPONSE, *PIXIPC_HANDSHAKE_RESPONSE;

typedef enum _IX_IPC_HOOK_EVENT_KIND
{
    IxIpcHookEventUnknown = 0,
    IxIpcHookEventNt = 1,
    IxIpcHookEventWinsock = 2,
    IxIpcHookEventKi = 3,
    IxIpcHookEventExceptionLowNoise = 4,
    IxIpcHookEventExceptionHighPriv = 5,
    IxIpcHookEventIntegrity = 6,
    IxIpcHookEventModule = 7
} IXIPC_HOOK_EVENT_KIND;

#define IXIPC_MAX_HOOK_API_NAME 64
#define IXIPC_MAX_HOOK_MODULE_NAME 32
#define IXIPC_MAX_HOOK_DATA_SAMPLE 512
#define IXIPC_MAX_HOOK_STACK_FRAMES 64
#define IXIPC_MAX_HOOK_ARGS 8

#define IXIPC_MAX_HOOK_POLICY_RULES 128u
#define IXIPC_MAX_HOOK_POLICY_IGNORE_DLLS 16u

#define IXIPC_HOOK_POLICY_VERSION 2u
#define IXIPC_HOOK_POLICY_FLAG_CLI_MODE 0x00000001u
#define IXIPC_HOOK_POLICY_FLAG_EXPLICIT_NT 0x00000002u
#define IXIPC_HOOK_POLICY_FLAG_IGNORE_PRIVATE 0x00000004u
#define IXIPC_HOOK_POLICY_FLAG_EXPLICIT_MODULE 0x00000008u
#define IXIPC_HOOK_POLICY_FLAG_EXPLICIT_WINSOCK 0x00000010u
#define IXIPC_HOOK_POLICY_FLAG_GUARD_DIRECT_SYSCALLS 0x00000020u

#define IXIPC_HOOK_POLICY_COMPONENT_NT 1u
#define IXIPC_HOOK_POLICY_COMPONENT_MODULE 2u
#define IXIPC_HOOK_POLICY_COMPONENT_WINSOCK 3u

#define IXIPC_HOOK_RULE_FLAG_LOG 0x00000001u
#define IXIPC_HOOK_RULE_FLAG_STACK_TRACE 0x00000002u
#define IXIPC_HOOK_RULE_FLAG_REGISTERS 0x00000004u
#define IXIPC_HOOK_RULE_FLAG_STACK_FABRICATE 0x00000008u

#define IXIPC_HOOK_METHOD_INLINE 0u
#define IXIPC_HOOK_METHOD_INT3 1u
#define IXIPC_HOOK_METHOD_IAT 2u
#define IXIPC_HOOK_METHOD_SHADOW_IAT 3u
#define IXIPC_HOOK_METHOD_VMT 4u
#define IXIPC_HOOK_METHOD_TRAP_FLAG 5u
#define IXIPC_HOOK_METHOD_DEBUG_REGISTER 6u

#define IXIPC_HOOK_ACTION_NONE 0u
#define IXIPC_HOOK_ACTION_DENY 1u
#define IXIPC_HOOK_ACTION_SILENT_DENY 2u

typedef struct _IX_IPC_HOOK_EVENT
{
    UINT32 Kind;
    UINT32 ProcessId;
    UINT32 ThreadId;
    UINT32 Operation;
    UINT64 Caller;
    UINT64 Context0;
    UINT64 Context1;
    UINT64 Context2;
    UINT64 Context3;
    UINT32 ArgCount;
    UINT32 DataSize;
    UINT64 Args[IXIPC_MAX_HOOK_ARGS];
    UINT32 StackCount;
    UINT32 CallerFlags;
    UINT32 Status;
    UINT32 Action;
    UINT64 Stack[IXIPC_MAX_HOOK_STACK_FRAMES];
    CHAR ApiName[IXIPC_MAX_HOOK_API_NAME];
    CHAR ModuleName[IXIPC_MAX_HOOK_MODULE_NAME];
    UINT8 DataSample[IXIPC_MAX_HOOK_DATA_SAMPLE];
} IXIPC_HOOK_EVENT, *PIXIPC_HOOK_EVENT;

typedef struct _IX_IPC_HOOK_POLICY_RULE
{
    UINT32 Component;
    UINT32 Action;
    UINT32 Flags;
    UINT32 DenyStatus;
    UINT32 HookMethod;
    UINT32 Reserved;
    CHAR ApiName[IXIPC_MAX_HOOK_API_NAME];
} IXIPC_HOOK_POLICY_RULE, *PIXIPC_HOOK_POLICY_RULE;

typedef struct _IX_IPC_QUERY_HOOK_POLICY_REQUEST
{
    UINT32 ProcessId;
    UINT32 Reserved0;
    UINT32 Reserved1;
    UINT32 Reserved2;
} IXIPC_QUERY_HOOK_POLICY_REQUEST, *PIXIPC_QUERY_HOOK_POLICY_REQUEST;

typedef struct _IX_IPC_QUERY_HOOK_POLICY_RESPONSE
{
    UINT32 PolicyVersion;
    UINT32 Flags;
    UINT32 RuleCount;
    UINT32 IgnoreDllCount;
    IXIPC_HOOK_POLICY_RULE Rules[IXIPC_MAX_HOOK_POLICY_RULES];
    CHAR IgnoreDlls[IXIPC_MAX_HOOK_POLICY_IGNORE_DLLS][IXIPC_MAX_HOOK_MODULE_NAME];
} IXIPC_QUERY_HOOK_POLICY_RESPONSE, *PIXIPC_QUERY_HOOK_POLICY_RESPONSE;

#define IXIPC_MAX_HOOK_EVENT_BATCH 8u

typedef struct _IX_IPC_HOOK_EVENT_BATCH
{
    UINT32 Count;
    UINT32 Reserved;
    IXIPC_HOOK_EVENT Events[IXIPC_MAX_HOOK_EVENT_BATCH];
} IXIPC_HOOK_EVENT_BATCH, *PIXIPC_HOOK_EVENT_BATCH;

#define IXIPC_HOOK_READY_FLAG_IPC_CONNECTED 0x00000001u
#define IXIPC_HOOK_READY_FLAG_WINSOCK 0x00000002u
#define IXIPC_HOOK_READY_FLAG_NT 0x00000004u
#define IXIPC_HOOK_READY_FLAG_KI 0x00000008u
#define IXIPC_HOOK_READY_FLAG_MODULE 0x00000010u
#define IXIPC_HOOK_READY_REQUIRED_MASK                                                                                 \
    (IXIPC_HOOK_READY_FLAG_IPC_CONNECTED | IXIPC_HOOK_READY_FLAG_WINSOCK | IXIPC_HOOK_READY_FLAG_NT |                  \
     IXIPC_HOOK_READY_FLAG_KI | IXIPC_HOOK_READY_FLAG_MODULE)

typedef struct _IX_IPC_NOTIFY_HOOK_READY_REQUEST
{
    UINT32 ProcessId;
    UINT32 ReadyMask;
    UINT32 Reserved0;
    UINT32 Reserved1;
} IXIPC_NOTIFY_HOOK_READY_REQUEST, *PIXIPC_NOTIFY_HOOK_READY_REQUEST;

typedef struct _IX_IPC_NOTIFY_HOOK_READY_RESPONSE
{
    UINT32 ProcessId;
    UINT32 ObservedMask;
    UINT32 RequiredMask;
    UINT32 PendingCommand;
} IXIPC_NOTIFY_HOOK_READY_RESPONSE, *PIXIPC_NOTIFY_HOOK_READY_RESPONSE;

typedef struct _IX_IPC_REGISTER_INSTRUMENTATION_RANGE_REQUEST
{
    UINT64 BaseAddress;
    UINT64 RegionSize;
    UINT32 Flags;
    UINT32 Reserved;
    CHAR Tag[IX_MAX_INSTRUMENTATION_TAG];
} IXIPC_REGISTER_INSTRUMENTATION_RANGE_REQUEST, *PIXIPC_REGISTER_INSTRUMENTATION_RANGE_REQUEST;

typedef struct _IX_IPC_REGISTER_HOOK_PATCH_REQUEST
{
    UINT64 PatchAddress;
    UINT32 PatchSize;
    UINT32 OriginalSize;
    UINT32 Flags;
    UINT32 Reserved;
    UINT8 OriginalBytes[IX_MAX_HOOK_PATCH_BYTES];
    CHAR Tag[IX_HOOK_PATCH_TAG_CHARS];
} IXIPC_REGISTER_HOOK_PATCH_REQUEST, *PIXIPC_REGISTER_HOOK_PATCH_REQUEST;

typedef struct _IX_REGISTER_PROCESS_INSTRUMENTATION_CALLBACK_REQUEST
{
    UINT32 ProcessId;
    UINT32 Flags;
    UINT64 CallbackAddress;
    UINT64 CallbackSize;
} IX_REGISTER_PROCESS_INSTRUMENTATION_CALLBACK_REQUEST, *PIX_REGISTER_PROCESS_INSTRUMENTATION_CALLBACK_REQUEST;

#define IX_HOOK_EVENT_OP_HOOK_INTEGRITY 1u
#define IX_HOOK_EVENT_OP_AMSI_PATCH 2u
#define IX_HOOK_EVENT_OP_ETW_PATCH 3u
#define IX_HOOK_EVENT_OP_LAUNCH_GATE_ENTRY 4u
#define IX_HOOK_EVENT_OP_LAUNCH_GATE_TLS_CALLBACK 5u
#define IX_HOOK_EVENT_OP_PIC_DIRECT_SYSCALL 6u
#define IX_HOOK_EVENT_OP_IX_SELF_MAP_ENTRY 7u
#define IX_HOOK_EVENT_OP_NTDLL_DOUBLE_LOAD 8u
#define IX_HOOK_EVENT_OP_NTDLL_EAT_ACCESS 9u
#define IX_HOOK_EVENT_OP_DIRECT_SYSCALL_PAGE 10u
#define IX_HOOK_EVENT_OP_DIRECT_SYSCALL_ACCESS 11u
#define IX_SELF_MAP_KIND_RUNTIME_STATE 1u
#define IX_SELF_MAP_KIND_INDIRECT_HANDLE 2u
#define IX_SELF_MAP_KIND_HOOK_PATCH 3u
#define IX_SELF_MAP_KIND_SYSCALL_STUB 4u
#define IX_SELF_MAP_KIND_LAUNCH_GATE_PAGE 5u
#define IX_SELF_MAP_KIND_LAUNCH_GATE_CONTEXT 6u
#define IX_SELF_MAP_KIND_CALLBACK 7u
#define IX_SELF_MAP_KIND_SNAPSHOT_SUMMARY 8u
#define IX_SELF_MAP_FLAG_EXECUTABLE 0x00000001u
#define IX_SELF_MAP_FLAG_OWNED 0x00000002u
#define IX_SELF_MAP_FLAG_GUARDED 0x00000004u
#define IX_SELF_MAP_FLAG_REFERENCE 0x00000008u
#define IX_SELF_MAP_FLAG_MEMORY_COMMIT 0x00000010u
#define IX_SELF_MAP_FLAG_MEMORY_PRIVATE 0x00000020u
#define IX_SELF_MAP_FLAG_MEMORY_IMAGE 0x00000040u
#define IX_SELF_MAP_FLAG_MEMORY_MAPPED 0x00000080u
#define IX_SELF_MAP_FLAG_MEMORY_WRITE 0x00000100u
#define IX_SELF_MAP_FLAG_MEMORY_GUARD 0x00000200u
#define IX_SELF_MAP_FLAG_TRUNCATED 0x80000000u

#define IX_HOOK_CALLER_FLAG_ALL_SYSTEM 0x00000001u
#define IX_HOOK_CALLER_FLAG_HAS_UNMAPPED 0x00000002u
#define IX_HOOK_CALLER_FLAG_HAS_PROCESS_IMAGE 0x00000004u
#define IX_HOOK_CALLER_FLAG_HAS_NONSYSTEM_DLL 0x00000008u
#define IX_HOOK_CALLER_FLAG_HAS_OWN_MODULE 0x00001000u
#define IX_HOOK_CALLER_FLAG_PRIVATE_EXEC_NO_UNWIND 0x00002000u
#define IX_HOOK_CALLER_FLAG_PRIVATE_EXEC_DYNAMIC_UNWIND 0x00004000u
#define IX_HOOK_CALLER_FLAG_IMAGE_MISSING_UNWIND_METADATA 0x00008000u
#define IX_HOOK_CALLER_IMMED_SHIFT 4u
#define IX_HOOK_CALLER_IMMED_MASK 0x000000F0u
#define IX_HOOK_CALLER_DEEP_SHIFT 8u
#define IX_HOOK_CALLER_DEEP_MASK 0x00000F00u
#define IX_HOOK_CALLER_COMPONENT_SHIFT 16u
#define IX_HOOK_CALLER_COMPONENT_MASK 0x000F0000u
#define IX_HOOK_CALLER_REPEAT_SHIFT 20u
#define IX_HOOK_CALLER_REPEAT_MASK 0xFFF00000u
#define IX_HOOK_CALLER_KIND_UNKNOWN 0u
#define IX_HOOK_CALLER_KIND_UNMAPPED 1u
#define IX_HOOK_CALLER_KIND_SYSTEM_DLL 2u
#define IX_HOOK_CALLER_KIND_PROCESS_IMAGE 3u
#define IX_HOOK_CALLER_KIND_OWN_MODULE 4u
#define IX_HOOK_CALLER_KIND_NONSYSTEM_DLL 5u
#define IX_HOOK_COMPONENT_UNKNOWN 0u
#define IX_HOOK_COMPONENT_WINSOCK 1u
#define IX_HOOK_COMPONENT_NT 2u
#define IX_HOOK_COMPONENT_KI 3u
#define IX_HOOK_COMPONENT_MODULE 4u
#define IX_HOOK_COMPONENT_INTEGRITY 5u

typedef union _IX_IPC_PAYLOAD
{
    IXIPC_HANDSHAKE_REQUEST HandshakeRequest;
    IXIPC_HANDSHAKE_RESPONSE HandshakeResponse;
    IXIPC_HOOK_EVENT HookEvent;
    IXIPC_HOOK_EVENT_BATCH HookEventBatch;
    IXIPC_NOTIFY_HOOK_READY_REQUEST NotifyHookReadyRequest;
    IXIPC_NOTIFY_HOOK_READY_RESPONSE NotifyHookReadyResponse;
    IXIPC_REGISTER_INSTRUMENTATION_RANGE_REQUEST RegisterInstrumentationRangeRequest;
    IXIPC_REGISTER_HOOK_PATCH_REQUEST RegisterHookPatchRequest;
    IX_REGISTER_PROCESS_INSTRUMENTATION_CALLBACK_REQUEST RegisterProcessInstrumentationCallbackRequest;
    IXIPC_QUERY_HOOK_POLICY_REQUEST QueryHookPolicyRequest;
    IXIPC_QUERY_HOOK_POLICY_RESPONSE QueryHookPolicyResponse;
} IXIPC_PAYLOAD, *PIXIPC_PAYLOAD;

typedef struct _IX_IPC_PACKET
{
    UINT32 Magic;
    UINT32 Version;
    UINT32 PacketType;
    UINT32 Command;
    UINT32 Sequence;
    UINT32 Status;
    IXIPC_PAYLOAD Payload;
} IXIPC_PACKET, *PIXIPC_PACKET;

#define BLIND_SDK_VERSION_MAJOR 0u
#define BLIND_SDK_VERSION_MINOR 2u
#define BLIND_SDK_IPC_VERSION IXIPC_VERSION
#define BLIND_SDK_READY_CORE_MASK                                                                                      \
    (IXIPC_HOOK_READY_FLAG_IPC_CONNECTED | IXIPC_HOOK_READY_FLAG_NT | IXIPC_HOOK_READY_FLAG_KI)
#define BLIND_SDK_READY_FULL_MASK IXIPC_HOOK_READY_REQUIRED_MASK

#endif
